[tool.isort]
skip_glob = ["*/build/*"]
known_third_party = ["PIL", "block", "caffe2", "coco_caption_eval", "common", "config", "cv2", "dataset_utils", "datasets", "demjson", "eval_model", "git", "global_variables", "h5py", "main", "maskrcnn_benchmark", "matplotlib", "numpy", "pycocoevalcap", "pytorch_pretrained_bert", "recommonmark", "requests", "setuptools", "skimage", "sklearn", "sphinx_rtd_theme", "tensorboardX", "top_down_bottom_up", "torch", "torchtext", "torchvision", "tqdm", "train_model", "transformers", "utils", "yaml"]
multi_line_output = 3
line_length = 88
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
