dataset_config:
  vizwiz:
    return_info: true
    image_features:
          train:
          - /private/home/vedanuj/projects/pythia-internal/data/vizwiz/detectron_fix_100/fc6
          - /private/home/vedanuj/projects/pythia-internal/data/vizwiz/detectron_fix_100/fc6
          val:
          - /private/home/vedanuj/projects/pythia-internal/data/vizwiz/detectron_fix_100/fc6
          test:
          - /private/home/vedanuj/projects/pythia-internal/data/vizwiz/detectron_fix_100/fc6
    imdb_files:
          train:
          - imdb/vizwiz/imdb_vizwiz_train.npy
          - imdb/vizwiz/imdb_vizwiz_val.npy
    processors:
      # Stop fasttext from loading by overriding the context_processor
      context_processor:
        type: simple_word
        params: {}
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
