includes:
- ./defaults.yaml

dataset_config:
  vqa2:
    image_features:
        train:
        -  /private/home/vedanuj/pythia/data/coco/detectron_fix_resnext152/features_train2014
        -  /private/home/vedanuj/pythia/data/coco/detectron_fix_resnext152/features_val2014
    imdb_files:
        train:
        - imdb/vqa/imdb_train2014.npy
        - imdb/vqa/imdb_val2014.npy
    return_info: true
