includes:
- ../configs/visual_bert/coco_pretrain.yml
- ../configs/visual_bert/vqa2.yml

model_attributes:
  visual_bert:
    training_head_type: pretraining,vqa

scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 3000
    t_total: 33000
  
training_parameters:
  max_updates: 34000
  monitored_metric: vqa2/vqa_accuracy
  metric_minimize: false