includes:
- common/defaults/configs/datasets/reasoning/visual_entailment.yml
- ../configs/visual_bert/coco_pretrain.yml

model_config:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: visual_entailment
    losses:
    - type: cross_entropy
    metrics:
    - accuracy

dataset_config:
  visual_entailment:
    return_info: true
    image_features:
        train:
        - /private/home/vedanuj/projects/pythia-internal/data/flickr30k/detectron_fix_100/fc6
        - /private/home/vedanuj/projects/pythia-internal/data/flickr30k/detectron_fix_100/fc6
        val:
        - /private/home/vedanuj/projects/pythia-internal/data/flickr30k/detectron_fix_100/fc6
        test:
        - /private/home/vedanuj/projects/pythia-internal/data/flickr30k/detectron_fix_100/fc6
    imdb_files:
        train:
        - imdb/visual_entailment/snli_ve_train.jsonl
        - imdb/visual_entailment/snli_ve_dev.jsonl
        val:
        - imdb/visual_entailment/snli_ve_test.jsonl
        test:
        - imdb/visual_entailment/snli_ve_test.jsonl
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6000
    num_training_steps: 60000

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  pretrained_mapping:
    bert: bert
