includes:
- common/defaults/configs/datasets/vqa/vqa2.yml
- ../configs/visual_bert/coco_pretrain.yml

model_attributes:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: vqa
    losses:
    - type: logit_bce

dataset_attributes:
  vqa2:
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
        
scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 6000
    t_total: 60000
    
training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  pretrained_mapping:
    bert.bert: bert.bert
