dataset_config:
  stvqa:
    data_root_dir: ../data
    image_features:
      train:
      - m4c_stvqa_obj_frcn_features/train,m4c_stvqa_ocr_en_frcn_features/train
      val:
      - m4c_stvqa_obj_frcn_features/train,m4c_stvqa_ocr_en_frcn_features/train
      test:
      - m4c_stvqa_obj_frcn_features/test_task3,m4c_stvqa_ocr_en_frcn_features/test_task3
    imdb_files:
      train:
      - imdb/m4c_stvqa/imdb_subtrain.npy
      val:
      - imdb/m4c_stvqa/imdb_subval.npy
      test:
      - imdb/m4c_stvqa/imdb_test_task3.npy
    processors:
      text_processor:
        type: m4c_bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_length: 20
      answer_processor:
        type: m4c_answer
        params:
          vocab_file: m4c_vocabs/stvqa/fixed_answer_vocab_stvqa_5k.txt
          preprocessor:
            type: simple_word
            params: {}
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 50
          max_copy_steps: 12
          num_answers: 10
      copy_processor:
        type: copy
        params:
          max_length: 100
      phoc_processor:
        type: phoc
        params:
          max_length: 50

training:
    monitored_metric: m4c_stvqa/stvqa_accuracy
    metric_minimize: false
