# Use soft copy
dataset_config:
  m4c_textcaps:
    image_features:
      train:
      - open_images/detectron_fix_100/fc6/train,m4c_textvqa_ocr_en_frcn_features/train_images
      val:
      - open_images/detectron_fix_100/fc6/train,m4c_textvqa_ocr_en_frcn_features/train_images
      test:
      - open_images/detectron_fix_100/fc6/test,m4c_textvqa_ocr_en_frcn_features/test_images
    imdb_files:
      train:
      - imdb/m4c_textcaps/imdb_train.npy
      val:
      - imdb/m4c_textcaps/imdb_val_filtered_by_image_id.npy  # only one sample per image_id
      test:
      - imdb/m4c_textcaps/imdb_test_filtered_by_image_id.npy  # only one sample per image_id
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          max_length: 1
      answer_processor:
        type: m4c_caption
        params:
          vocab_file: m4c_captioner_vocabs/textcaps/vocab_textcap_threshold_10.txt
          preprocessor:
            type: simple_word
            params: {}
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 50
          max_copy_steps: 30
          num_answers: 1
      copy_processor:
        type: copy
        params:
          max_length: 100
      phoc_processor:
        type: phoc
        params:
          max_length: 50

optimizer:
  params:
    eps: 1.0e-08
    lr: 1e-4
    weight_decay: 0
  type: Adam
training:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    lr_steps:
    - 10000
    - 11000
    lr_ratio: 0.1
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 1000
    max_iterations: 12000
    batch_size: 128
    num_workers: 8
    task_size_proportional_sampling: true
    monitored_metric: m4c_textcaps/textcaps_bleu4
    metric_minimize: false
