dataset_config:
  masked_mmimdb:
    data_root_dir: ../data
    image_depth_first: false
    fast_read: false
    image_features:
        train:
        - /private/home/asg/features/mm_imdb/detectron_fix_100_resnext152/
        val:
        - /private/home/asg/features/mm_imdb/detectron_fix_100_resnext152/
        test:
        - /private/home/asg/features/mm_imdb/detectron_fix_100_resnext152/
    imdb_files:
        train:
        - /private/home/asg/pythia/data/imdb/mm_imdb/train.jsonl
        val:
        - /private/home/asg/pythia/data/imdb/mm_imdb/dev.jsonl
        test:
        - /private/home/asg/pythia/data/imdb/mm_imdb/test.jsonl
    features_max_len: 100
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 256
    return_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
