includes:
- common/defaults/configs/datasets/captioning/masked_coco.yml
- common/defaults/configs/models/vilbert.yml

dataset_attributes:
  masked_coco:
    return_info: true

    image_features:
        train:
        -  /private/home/asg/features/coco/detectron_fix_100_resnext152/train_val_2014
        -  /private/home/asg/features/coco/detectron_fix_100_resnext152/train_val_2014
    imdb_files:
        train:
        - imdb/coco_captions/imdb_karpathy_train_by_image.npy
        - imdb/coco_captions/imdb_coco_full_val.npy

model_attributes:
  vilbert:
    training_head_type: pretraining

dataset_attributes:
  masked_coco:
    return_info: true
    use_image_feature_masks: true

optimizer_attributes:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler_attributes:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 11000

training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 11000
  find_unused_parameters: true