includes:
- common/defaults/configs/datasets/vqa/masked_vqa2.yaml
- common/defaults/configs/models/vilbert.yaml

model_config:
  vilbert:
    training_head_type: pretraining

dataset_config:
  masked_vqa2:
    image_features:
      train:
      -  /private/home/asg/features/coco/detectron_fix_100_resnext152/train_val_2014
      -  /private/home/asg/features/coco/detectron_fix_100_resnext152/train_val_2014
    imdb_files:
      train:
      - imdb/vqa/imdb_train2014.npy
      - imdb/vqa/imdb_val2014.npy
    return_info: true
    use_image_feature_masks: true

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 11000

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 11000
  find_unused_parameters: true
