includes:
- common/defaults/configs/datasets/vqa/masked_vqa2.yml
- common/defaults/configs/models/vilbert.yml

model_attributes:
  vilbert:
    training_head_type: pretraining

dataset_attributes:
  masked_vqa2:
    imdb_files:
      train:
      - imdb/vqa/imdb_train2014_len_coco.npy
    return_info: true
    use_image_feature_masks: true

optimizer_attributes:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler_attributes:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 11000

training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 11000
  find_unused_parameters: true