includes:
- common/defaults/configs/datasets/reasoning/mmimdb.yml
- common/defaults/configs/models/vilbert.yml

model_attributes:
  vilbert:
    training_head_type: mmimdb
    losses:
    - type: logit_bce
    metrics:
    # - accuracy
    - macro_f1
    - micro_f1

dataset_attributes:
  mmimdb:
    return_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 256

optimizer_attributes:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 2000
    t_total: 88000

training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  pretrained_mapping:
    bert.bert: bert.bert
  find_unused_parameters: true
