includes:
- common/defaults/configs/datasets/reasoning/visual_entailment.yml
- ../configs/vilbert/coco_pretrain.yml

model_attributes:
  vilbert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: visual_entailment
    losses:
    - type: cross_entropy
    metrics:
    - accuracy

dataset_attributes:
  visual_entailment:
    return_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
        
scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 6000
    t_total: 60000
    
training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  pretrained_mapping:
    bert.bert: bert.bert
  find_unused_parameters: true
