includes:
- common/defaults/configs/datasets/vqa/vqa2.yml
- common/defaults/configs/models/vilbert.yml

model_attributes:
  vilbert:
    training_head_type: vqa
    losses:
    - type: logit_bce
    metrics:
    - vqa_accuracy

dataset_attributes:
  vqa2:
    return_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer_attributes:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 6000
    t_total: 60000
    
training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 60000
  pretrained_mapping:
    bert.bert: bert.bert
  find_unused_parameters: true
