dataset_config:
  masked_coco:
    return_info: true

    image_features:
        train:
        -  /private/home/asg/features/coco/detectron_fix_100_resnext152/train_val_2014
        -  /private/home/asg/features/coco/detectron_fix_100_resnext152/train_val_2014
    imdb_files:
        train:
        - imdb/coco_captions/imdb_karpathy_train_by_image.npy
        - imdb/coco_captions/imdb_coco_full_val.npy
/
