includes:
- common/defaults/configs/datasets/captioning/masked_coco.yml

model_attributes:
  pythia_bert:
    combine_embeddings: true
    model_data_dir: ../data/
    bert_model_name: bert-base-uncased
    training_head_type: pretraining
    visual_embedding_dim: 2048
    special_visual_initialize: true
    hard_cap_seq_len: null
    cut_first: text
    embedding_strategy: plain
    bypass_transformer: false
    output_attentions: false
    output_hidden_states: false
    text_only: false
    random_initialize: false
    pretrained_bert: false
    metrics:
    - vqa_accuracy
    classifier:
      type: logit
      params:
        img_hidden_dim: 5000
        text_hidden_dim: 300
    image_feature_embeddings:
    - embed_dim: 768
      kdim: 768
      vdim: 768
      num_heads: 8
      dropout: 0.1
    image_feature_dim: 2048
    image_feature_projection:
      module: linear
      in_dim: 2048
      out_dim: 768
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: detectron/fc6/fc7_b.pkl
        weights_file: detectron/fc6/fc7_w.pkl
    image_text_modal_combine:
      type: non_linear_element_multiply
      params:
        dropout: 0
        hidden_dim: 768
    text_embeddings:
    - embed_dim: 768
      kdim: 768
      vdim: 768
      num_heads: 8
      dropout: 0.1

dataset_attributes:
  masked_coco:
    return_info: true

optimizer_attributes:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 2000
    t_total: 24000
    
training_parameters:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 24000