includes:
- common/defaults/configs/datasets/vqa/masked_vqa2.yaml
- ../configs/pythia_bert/coco_pretrain.yaml

dataset_config:
  masked_vqa2:
    imdb_files:
      train:
      - imdb/vqa/imdb_train2014_len_coco.npy
    return_info: true
