includes:
- common/defaults/configs/datasets/reasoning/visual_entailment.yaml
- ../configs/pythia_bert/vqa2.yaml

model_config:
  pythia_bert:
    training_head_type: visual_entailment
    losses:
    - type: cross_entropy
    metrics:
    - accuracy

dataset_config:
  visual_entailment:
    return_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6000
    num_training_steps: 60000

training:
  monitored_metric: visual_entailment/accuracy
  metric_minimize: false
