includes:
- common/defaults/configs/datasets/reasoning/visual_entailment.yml
- ../configs/pythia_bert/vqa2.yml

model_attributes:
  pythia_bert:
    training_head_type: visual_entailment
    losses:
    - type: cross_entropy
    metrics:
    - accuracy

dataset_attributes:
  visual_entailment:
    return_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
        
scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 6000
    t_total: 60000
    
