includes:
- common/defaults/configs/datasets/vqa/vqa2.yml
- ../configs/pythia_bert/coco_pretrain.yml

dataset_attributes:
  vqa2:
    image_features:
      train:
      - coco/detectron_fix_100/fc6/train_val_2014
      val:
      - coco/detectron_fix_100/fc6/train_val_2014
      test:
      - coco/detectron_fix_100/fc6/test2015
    processors:
        text_processor:
          type: bert_tokenizer
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0
            max_seq_length: 128
 
model_attributes:
  pythia_bert:
    training_head_type: vqa
    losses:
    - type: logit_bce

scheduler_attributes:
  type: warmup_linear
  params:
    warmup_steps: 2400
    t_total: 24000
    
training_parameters:
  batch_size: 512
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 24000
  pretrained_mapping:
    word_embedding: word_embedding
    text_embedding: text_embedding
    feature_projection: feature_projection
    image_feature_encoders: image_feature_encoders
    image_feature_embeddings_list: image_feature_embeddings_list
    image_text_multi_modal_combine_layer: image_text_multi_modal_combine_layer
    pooler: pooler
